### ISSUE TITLE
.NET Core Buildpack

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-buildpacks#100]
Are there any plans in the near future to add the [.NET Core buildpack](https://github.com/cloudfoundry-incubator/dotnet-core-buildpack) to the documentation? If so, would you merge a PR regarding this buildpack?

**Comment by bentarnoff** [comment]
Thanks @mastertinner, we should absolutely document the .NET Core buildpack. I'll bring my colleague @jncd in on this, because she's taking the lead on Buildpacks. In the meantime, please feel free to submit any PRs that you think might be helpful.

**Comment by sclevine** [comment]
@jncd This buildpack will be an official system buildpack soon. Let me know if you have some time this week to coordinate documenting it.

**Comment by mastertinner** [comment]
Solved by #102 and #103.
