### ISSUE TITLE
Grails java buildpack doesn't define what service info is 

### ISSUE THREAD

**Issue by Omnipresent** [cloudfoundry/docs-buildpacks#101]
The page here: http://docs.run.pivotal.io/buildpacks/java/grails-service-bindings.html#auto has the following line

```
def dbInfo = cloud?.getServiceInfo('myapp-mysql')
```

But it doesn't define what `myapp-mysql` is? Is it name of the service or name of the app. 

While following this example I had setup the `mysql` service but the connection info failed with error: 

> No service with id cf-sample found

I push the app with command

```
➜  cf-sample git:(all-buildconfig) ✗ cf push cf-sample -n cf-sample
```

Output of  `manifest.yml`, `apps` and `services`

```
➜  cf-sample git:(all-buildconfig) ✗ cat manifest.yml
---
applications:
  - name: cfsample
    memory: 1G
    instances: 1
    path: target/cf-sample-0.1.war
    buildpack: java_buildpack
    services:
      - mysql
➜  cf-sample git:(all-buildconfig) ✗ cf apps
Getting apps in org pcfdev-org / space pcfdev-space as user...
OK

name        requested state   instances   memory   disk   urls
cf-sample   started           0/1         1G       512M   cf-sample.local.pcfdev.io
➜  cf-sample git:(all-buildconfig) ✗ cf services
Getting services in org pcfdev-org / space pcfdev-space as user...
OK

name    service   plan    bound apps   last operation
mysql   p-mysql   512mb   cf-sample    create succeeded
```

What should I put in `def dbInfo = cloud?.getServiceInfo('<what goes here??>')` based on the above?

**Comment by bentarnoff** [comment]
Thanks for this, @Omnipresent. @sclevine any thoughts on this?

**Comment by bentarnoff** [comment]
Sorry, I meant to ask @nebhale

**Comment by Omnipresent** [comment]
FWIW, what worked for me is that string in `cloud?.getServiceInfo('myapp-mysql')` should match the name column for a service when listing services with `cf services`

For example:

```
➜  cf-sample git:(master) cf services
Getting services in org pcfdev-org / space pcfdev-space as user...
OK

name       service      plan       bound apps   last operation
mysql      p-mysql      512mb      cf-sample    create succeeded
rabbitmq   p-rabbitmq   standard   cf-sample    create succeeded
```
For the above case the code for both would be

```
def dbInfo = cloud?.getServiceInfo('rabbitmq')
def dbInfo = cloud?.getServiceInfo('mysql')
```

**Comment by bentarnoff** [comment]
Thanks @nebhale. @Omnipresent, I've added an explanatory note that I hope clarifies the topic for you. You can see the new content at our staging site here: http://docs-cloudfoundry-staging.cfapps.io/buildpacks/java/grails-service-bindings.html#manual. I'm closing this issue for now but please don't hesitate to get in touch with any further feedback.
