### ISSUE TITLE
Remove Java build integration page with all tools currently unsupported

### ISSUE THREAD

**Issue by mtthwcmpbll** [cloudfoundry/docs-buildpacks#131]
We should remove the documentation page describing Maven and Gradle integration at `/java/build-tool-int.html.md.erb`.  I spoke with @nebhale last week and these have not been migrated to the current `cf-java-client` repo in the move to version 2.x, so there is no official repo or documentation to point folks to for further information on these tools.  We can add a new page to cover future java build tools if/when those become available.

**Comment by animatedmax** [comment]
build-tool-int.html.md.erb has been removed 
http://docs-cloudfoundry-staging.cfapps.io/buildpacks/java/index.html
