### ISSUE TITLE
Where is bp.log?

### ISSUE THREAD

**Issue by randala** [cloudfoundry/docs-buildpacks#137]
According to the doc below, bp.log should be written to app/.bp/logs/
https://docs.cloudfoundry.org/buildpacks/php/gsg-php-usage.html#troubleshooting

I do not even see a logs folder:

vcap@289b9ee6-5e45-4b43-5396-aa673b71f738:~/app/.bp$ pwd
/home/vcap/app/.bp
vcap@289b9ee6-5e45-4b43-5396-aa673b71f738:~/app/.bp$ ls -al
total 16
drwxr-xr-x 4 vcap vcap 4096 Apr  5 21:05 .
drwxr-xr-x 9 vcap root 4096 Apr  5 21:05 ..
drwxr-xr-x 2 vcap vcap 4096 Apr  5 21:05 bin
drwxr-xr-x 3 vcap vcap 4096 Apr  5 21:05 lib
vcap@289b9ee6-5e45-4b43-5396-aa673b71f738:~/app/.bp$

**Comment by bentarnoff** [comment]
Hey @randala thanks for this. @sclevine do you have any thoughts on this issue?

**Comment by dgodd** [comment]
@randala Do you know which buildpack version you are using? Where are you pushing to? Is there anything special about your app? For instance pushing the most simple php app (just an index.php file) to cf using buildpack version v4.3.22, after pushing and ssh-ing in, I can run

```
vcap@442c99e8-a042-4770-5bc3-cba405183097:~$ find app/.bp/logs/
app/.bp/logs/
app/.bp/logs/bp.log
```

and see that `app/.bp/logs/bp.log` exists.

**Comment by bentarnoff** [comment]
@randala It's been awhile since we've heard from you, so I'm closing this issue. Please feel free to re-open it or raise another issue if you have further comments or concerns.
