### ISSUE TITLE
Broken links in the BOSH Custom Trusted Certificate Support section of docs-buildpacks/java/index.html.md.erb

### ISSUE THREAD

**Issue by yshewchuk** [cloudfoundry/docs-buildpacks#145]
The two links in the text: 

Alternatively, you can modify the buildpack by setting the enabled property to true in config/container_certificate_trust_store.yml. For more information, see the Java buildpack repository on GitHub.

Appear to be broken.

**Comment by animatedmax** [comment]
Hi @yshewchuk 
Thank you for raising this issue. We've removed these outdated links.
