### ISSUE TITLE
The sample in java-client.html.md.erb won't build

### ISSUE THREAD

**Issue by jamsden** [cloudfoundry/docs-buildpacks#157]
The maven dependencies don't match the Java source code. For example, the CloudFoundryClient class isn't defined given those dependencies.

**Comment by nebhale** [comment]
@jamsden I'm not on the doc team, but dependencies can be found [here](https://github.com/cloudfoundry/cf-java-client#dependencies) and example code can be found [here](https://github.com/cloudfoundry/cf-java-client#usage).

**Comment by cf-pub-tools** [comment]
Hi @jamsden 

This documentation repository is maintained by technical writers, not developers or support engineering. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.

For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io

Thank you.
