### ISSUE TITLE
documented /bin/package extension is unused/deprecated

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-buildpacks#16]
The current doc at https://github.com/cloudfoundry/docs-buildpacks/blob/3c4455d4aa34d9410956bd2e0689a8abd7f98ee3/custom.html.md.erb#L96-L115 describes the `/bin/package` CF extension

However:
- the ruby buildpack example does not support the `/bin/package` command anymore, it has been replaced by the usage of the https://github.com/cf-buildpacks/buildpack-packager , see https://github.com/cloudfoundry/nodejs-buildpack/commit/8d358f9f5348db536513cb7181de4fb04eb8aea8 and https://github.com/cloudfoundry/ruby-buildpack/issues/29#issuecomment-70891929
- the java buildpack offers a different way to package the offline buildpack zip: https://github.com/cloudfoundry/java-buildpack/#offline-package
- the documentation does not explain where the `/bin/package` extension is supposed to be called and what benefit this extension provides (besides that the doc does not state where the zip files should be written to)

As a result, this seems to rather create confusion in the community 
https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/OWg4JXziyO0/0yxBjvjSRWQJ and https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/UR7h5MroGE4/RmPqh46V5QIJ

Suggesting to remove the /bin/package` extension from the documentation until status of this extension is made clear, and rather point to

**Comment by jchesterpivotal** [comment]
Hi @gberche-orange. 

We in the CF Buildpacks team updated the packaging mechanism late last year, but we failed to update the documentation, which has led to equivalent reports on the [ruby](https://github.com/cloudfoundry/ruby-buildpack/issues/29), [nodejs](https://github.com/cloudfoundry/nodejs-buildpack/issues) and [python](https://github.com/cloudfoundry/python-buildpack/issues/11) buildpacks. Those issues were resolved yesterday and the READMEs should now be up to date with how packaging works.

Updating the master documentation in docs-buildpacks is underway today.

Java buildpack is managed by a different team and is a completely independent implementation.

**Comment by gberche-orange** [comment]
Thanks @jchesterpivotal for your response, and sorry for the extra noise as you planned on working on docs today.

**Comment by jchesterpivotal** [comment]
Not at all. We take it as a very promising sign that the community is keen to help us correct oversights.

**Comment by jchesterpivotal** [comment]
FYI, the Tracker story above was assigned to the Docs team. We have [a matching story](https://www.pivotaltracker.com/story/show/86947488) in our own Tracker.

**Comment by elenasharma** [comment]
Closed with https://github.com/cloudfoundry/docs-buildpacks/pull/18.

**Comment by gberche-orange** [comment]
thanks!
