### ISSUE TITLE
https://docs.cloudfoundry.org/buildpacks/ruby/ruby-environment.html : confusion re environment variable name

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/docs-buildpacks#172]
```
RACK_ENV | The Rack deployment environment, which governs the middleware loaded to run the app. Valid value are development, test, and production. Example: RAILS_ENV=production
```

Is the env var named `RACK_ENV` or `RAILS_ENV` ?

**Comment by animatedmax** [comment]
Hi @ericpromislow Both `RACK_ENV` and `RAILS_ENV` environment variables exist, and we have updated the https://docs.cloudfoundry.org/buildpacks/ruby/ruby-environment.html page with the missing information. Thanks!
