### ISSUE TITLE
Configuring ForceHttps via Staticfile

### ISSUE THREAD

**Issue by dmarmugi** [cloudfoundry/docs-buildpacks#193]
Hi, 
Currently the docs say to force https on the Staticfile buildpack to: 
> set the <code>FORCE_HTTPS</code> environment variable to <code>true</code>

It appears you can also set it via a Staticfile parameter (from `src/staticfile/finalize/finalize.go`): 
```go
type Staticfile struct {
...
    ForceHTTPS            bool   `yaml:"force_https"```

Can/should the Staticfile configuration method be added to the docs? 

Thanks,
-David

**Comment by bentarnoff** [comment]
Hey @dmarmugi thanks for this! We've updated the docs accordingly.
