### ISSUE TITLE
"Specify a .NET Framework Version" contains outdated .csproj snippet

### ISSUE THREAD

**Issue by skmichaelson** [cloudfoundry/docs-buildpacks#202]
To specify a version of the .NET runtime, you should use a <PropertyGroup> instead of a package reference. See the [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) for more details.

**Comment by bentarnoff** [comment]
Looks like this change has been taken care of by https://github.com/cloudfoundry/docs-buildpacks/pull/204, so I'm closing. Thanks.
