### ISSUE TITLE
Microsoft is ending .NET Core 2.0 support

### ISSUE THREAD

**Issue by skmichaelson** [cloudfoundry/docs-buildpacks#203]
For more details, see this [article on Microsoft's blog](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/). I'm not sure if any action is necessary, but this may be relevant for the .NET core buildpack docs.

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @skmichaelson. @sclevine can you speak to whether this will impact the .NET Core Buildpack docs at https://docs.cloudfoundry.org/buildpacks/dotnet-core/? Thanks.

**Comment by sclevine** [comment]
We have a single version of the .NET Core 2.0 SDK still included in the buildpack. We plan to deprecate it soon.

**Comment by kdolor-pivotal** [comment]
@skmichaelson Based on https://github.com/cloudfoundry/dotnet-core-buildpack/releases, it looks like dotnet core 2.0 was removed from the dotnet-core-buildpack in 2.2.8. 

Thanks for your feedback!
