### ISSUE TITLE
Incorrect documented filename for buildpacks.yml

### ISSUE THREAD

**Issue by adamzerella** [cloudfoundry/docs-buildpacks#219]
The documentation seen [here](https://docs.cloudfoundry.org/buildpacks/nginx/index.html#nginx) defines a filename of `buildpacks.yml` to be used, the `nginx-buildpack` is expecting the filename `buildpack.yml`. 

This causes the specified version in `buildpacks.yml` to be ignored.

**Comment by animatedmax** [comment]
Thank you, @adamzerella. We're accepting your PR #218 to correct this issue.
