### ISSUE TITLE
Documentation references non-existant API call

### ISSUE THREAD

**Issue by TildeWill** [cloudfoundry/docs-buildpacks#222]
https://github.com/cloudfoundry/docs-buildpacks/blob/ecd88f103c9f19fcf835ad4775b47ee2b5493320/java/configuring-service-connections/spring-service-bindings.html.md.erb#L185

`getServiceID` does not exist on the `cloud` instance in version 1.2.3

**Comment by sclevine** [comment]
@nebhale

**Comment by bentarnoff** [comment]
@scottfrederick Just wanted to bump this. Would you be able to speak to the above? Thanks!
