### ISSUE TITLE
Environment configure problem

### ISSUE THREAD

**Issue by zlycYichen** [cloudfoundry/docs-buildpacks#227]
My runtime environment error message is "You are using pip version 9.0.1, however version 18.1 is available.You should consider upgrading via the 'pip install --upgrade pip' command." How to configure it ? In runtime.txt or requirements.txt ?

**Comment by bentarnoff** [comment]
@zlycYichen Thanks for this. @sclevine would you be able to speak to the above?

**Comment by tylerphelan** [comment]
@zlycYichen this is a message coming from `pip`, not the python buildpack itself. There's no way to set your pip version so unfortunately the warning is unavoidable for now.

We have an issue in the python buildpack you can follow for this getting fixed: https://github.com/cloudfoundry/python-buildpack/issues/118

**Comment by Zanadar** [comment]
Closing in favor of https://github.com/cloudfoundry/python-buildpack/issues/118
