### ISSUE TITLE
Document `INSTALL_NODE=true` for server-side rendering in Dotnet with react

### ISSUE THREAD

**Issue by Zanadar** [cloudfoundry/docs-buildpacks#229]
Many devs want to push server-side rendered apps (react or angular usually) in dotnet. We should document this use case and note that they will have to specify `INSTALL_NODE=true` in their manifest to have node available in their app droplet.

https://github.com/cloudfoundry/docs-buildpacks/blob/84ebf376dc228fc5b489ae534c8425d0a9af7f90/dotnet-core/index.html.md.erb

**Comment by djoyahoy** [comment]
Issue was addressed in PR 231: 
https://github.com/cloudfoundry/docs-buildpacks/pull/231
