### ISSUE TITLE
Sentence is confusing

### ISSUE THREAD

**Issue by aglwallac** [cloudfoundry/docs-buildpacks#232]
within: docs-buildpacks/node/index.html.md.erb
at line 105: 

> "To vendor dependencies for an app using the Node.js buildpack, run `npm install`

  doesn't make any sense?

**Comment by vikafed** [comment]
Hi @aglwallac. We reached out to the Buildpacks team, and they confirmed that this sentence is technically accurate. `npm install` generates a `node_modules directory` of vendored modules. Thanks!
