### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by aglwallac** [cloudfoundry/docs-buildpacks#233]
in within: docs-buildpacks/node/index.html.md.erb
Lines 120-124?

> When vendoring apps for usage in offline environments, you must supply a lock file. For information 
about npm lockfiles, see [npm-package-locks](https://docs.npmjs.com/files/package-locks) in the NPM 
documentation. For information about the NPM lock file, see 
[package-lock.json](https://docs.npmjs.com/files/package-lock.json) in the NPM 
documentation. 

Unsure of double reference to npm lock files.  Maybe clarity in this sentence is needed.

**Comment by mjgutermuth** [comment]
Hi! It looks like this issue was addressed here: https://github.com/cloudfoundry/docs-buildpacks/commit/f566735726f02cb44f21b435c3b7e4ed03f21ccd

Thank you!
