### ISSUE TITLE
Staticfile Buildpack HSTS settings do not inherit

### ISSUE THREAD

**Issue by dmarmugi** [cloudfoundry/docs-buildpacks#253]
The Staticfile buildpack config-options include notes like 
> Note: Setting this property to true also makes http_strict_transport_security and http_strict_transport_security_include_subdomains default to true.
I'm not sure whether this is an issue with the docs or with the buildpack, 

but they're not true. 

For instance, this Staticfile doesn't include the `include_subdomains` toggle, and as a result it's missing from the returned header 
```
$ curl -si 'https://response-test.g4.app.cloud.comcast.net' | grep Strict                                                                                                                
Strict-Transport-Security: max-age=31536000; preload
$ cat Staticfile                                                                                                                                                                         
http_strict_transport_security_preload: true
http_strict_transport_security: true
```

This is behavior is borne out in the [code for the buildpack](https://github.com/cloudfoundry/staticfile-buildpack/blob/master/src/staticfile/finalize/data.go#L128-L130), which requires each toggle independently. 

I'll happily PR to either here or the buildpack if needed, once the intended behavior is confirmed.

**Comment by mlimonczenko** [comment]
Thank you, @dmarmugi! PR is preferred. Feel free to close this out and let me know when you've PRed.

**Comment by dmarmugi** [comment]
hi @mlimonczenko -- Sorry if I wasn't clear. I meant we can correct the documentation to align with the current behavior, or submit a PR to the buildpack to align the behavior with the current documentation, at your discretion. 
Thanks,
-david

**Comment by mlimonczenko** [comment]
I see. Thank you for the clarity.

**Comment by mlimonczenko** [comment]
Hello @dmarmugi,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
