### ISSUE TITLE
Some links are out of date in the Go section

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/docs-buildpacks#286]
This link and some of the other go-buildpack links don't work anymore.

https://github.com/cloudfoundry/docs-buildpacks/blob/f368671338fc7407642164e34d60b09a91c04807/go/index.html.md.erb#L54

**Comment by mjgutermuth** [comment]
Thanks for pointing this out, @ctlong! I wasn't able to find another sample Go app to use in its place, so I've just removed the bad links for now. If you happen to know of another app we could link to instead, please let me know and I can add it in.

**Comment by ctlong** [comment]
@mjgutermuth there are Go apps listed under https://github.com/cloudfoundry/go-buildpack/tree/master/fixtures that could conceivably replace the previous samples.

**Comment by mjgutermuth** [comment]
Thank you!
