### ISSUE TITLE
Document use of Cloud Native Buildpacks

### ISSUE THREAD

**Issue by loewenstein-sap** [cloudfoundry/docs-buildpacks#310]
Since [RFC0028](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0028-cnb-lifecycle.md) has been accepted, most of [the work to support Cloud Native Buildpacks](https://github.com/cloudfoundry/community/issues/891) has been implemented and merged.

With [RFC0031](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0031-system-cnb.md) even the support for Cloud Native Buildpacks as system buildpacks has been accepted and the [implementation](https://github.com/cloudfoundry/community/issues/965) is currently in review.

This issue is meant to track documentation efforts around the use of Cloud Native Buildpacks in Cloud Foundry and I would like to get this started with a proposal for the documentation structure.

Looking at the current structure of https://docs.cloudfoundry.org/buildpacks/, we have the following and need to make sure Cloud Native Buildpacks fit in this nicely and naturally:
- Buildpacks
  - Using buildpacks
    - Working with buildpacks in Cloud Foundry
    - Stack association
    - Pushing an app with multiple buildpacks
    - Using a proxy server
    - Supported binary dependencies
    - Configuring a production service
  - Binary buildpack
  - Go buildpack
  - ...
  - Customizing and developing buildpacks in Cloud Foundry

While there are similarities - in the end all versions of buildpacks are concerned with assembling an execution filesystem for different programming languages and environments - it seems to make sense to have separate documentation trees. We might want to make sure that similar topics are presented in a similar and recognizable way, but merging distinct information deeply will likely just create a bad experience for users of classical Cloud Foundry Buildpacks as well as Cloud Native Buildpacks.

We would propose to go for the following structure:
- Buildpacks
  - Cloud Foundry Buildpacks
    - Using buildpacks
      - Working with buildpacks in Cloud Foundry
      - Stack association
      - Pushing an app with multiple buildpacks
      - Using a proxy server
      - Supported binary dependencies
      - Configuring a production service
    - Binary buildpack
    - Go buildpack
    - ...
    - Customizing and developing buildpacks in Cloud Foundry
  - Cloud Native Buildpacks
    - What are Cloud Native Buildpacks?
      This would mainly focus on the historical background of buildpacks from v1 in Heroku to v2 in both Heroku and Cloud Foundry and finally v3 as a specification project in the CNCF and Paketo as a reference implementation from the Cloud Foundry Community.
    - Using buildpacks
      This would pick up the topics from the corresponding chapter and subchapters of the CF buildpacks part above where and when it makes sense.
    - Paketo buildpacks
      Instead of listing individual buildpacks, it seems to make more sense to reference the Paketo documentation more broadly.
      **Note**: Actually, this might stay blank for now, as there is currently no system buildpack support yet and once this is there, a separate RFC is needed that might decide to take Paketo buildpacks as (batteries included) system buildpacks for cf-deployment. Only then it makes sense to give Paketo this level of attention.
    - Developing your own buildpacks
      This would mainly reference buildpacks.io (and might reference paketo.io) and should not duplicate documentation that is separately available.

Additionally, we of course need to make sure that e.g. `cf cli` changes and `manifest.yaml` changes are documented in the proper places.

What you think?

**Comment by c0d1ngm0nk3y** [comment]
I started with that and have some questions:

Regarding the tree...

<img width="334" alt="tree" src="https://github.com/user-attachments/assets/2dcc4ad5-9ef5-4f68-bdfb-2750bff3ee9e">

* I wonder what the naming should be. After all, it is more a `v2` vs. `v3` thing, right?
* My impression is that the granularity is a bit strange. For `v2`, the buildpacks are described in detail and even per buildpack and `v3`, it is more an overview with referring to `paketo` (listing the buildpacks makes probably not much sense)

Regarding the index site....

<img width="578" alt="index_part1" src="https://github.com/user-attachments/assets/79fd834c-3722-47e9-b3c2-3d97b1e65b04">

<img width="578" alt="index_part2" src="https://github.com/user-attachments/assets/279e930f-4452-4ef0-8d6a-9db94947fff7">

* Having both in there is a bit to much for this page imho, wdyt? So we could...
  * Reduce the linked content, but that would reduce the available information for `v2`
  * Only mention `v2` which would feel odd to not mention the newer `v3` buildpacks

**Comment by loewenstein-sap** [comment]
@pspinrad have you had a chance to have a look?

**Comment by pspinrad** [comment]
Hi -- yes, I'd like to discuss, figure out how to do what we want with consistent naming and without changing source file structure as mentioned [here](https://github.com/cloudfoundry/docs-buildpacks/pull/312#issuecomment-2364129820).  I'd also like to include @anthonydahanne in the discussion.  Sound good?  What time zone are you in? (I'm in California)

**Comment by loewenstein-sap** [comment]
We're all located in CET, maybe start a doodle or similar with some times (in your mornings) that would work for you - would that work?

**Comment by pspinrad** [comment]
Sounds good-- [here's Doodle invite](https://doodle.com/meeting/participate/id/aAAYBOza), and I'll also send to Ralf and Anthony.

**Comment by c0d1ngm0nk3y** [comment]
> Sounds good-- [here's Doodle invite](https://doodle.com/meeting/participate/id/aAAYBOza), and I'll also send to Ralf and Anthony.

Thanks. Just pick any occurrence where some of our team (Jan, Pavel, Johannes, me) have time. That should be fine from our side.

**Comment by beyhan** [comment]
The docs has been release in https://docs.cloudfoundry.org/buildpacks/cnb/index.html. Can we close this?

**Comment by pspinrad** [comment]
Closing -- thanks, all!
