### ISSUE TITLE
.NET Core Buildpack page rendering issues

### ISSUE THREAD

**Issue by TimHess** [cloudfoundry/docs-buildpacks#323]
I think something is wrong with the markdown formatting in this document, here's what I see at https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html

![image](https://github.com/user-attachments/assets/13ab57b5-c6c7-40bb-8341-6adbb03c65ff)

**Comment by anita-flegg** [comment]
@TimHess , I have this mostly working. I will continue chipping away.

**Comment by anita-flegg** [comment]
I think this is all fixed. Closing.
