### ISSUE TITLE
Update docs for CF Gradle plugin

### ISSUE THREAD

**Issue by tonycapone** [cloudfoundry/docs-buildpacks#45]
Hello. While using the Gradle CF plugin, I noticed the [documentation](https://github.com/cloudfoundry/docs-buildpacks/blob/master/java/build-tool-int.html.md.erb) needs updated to include all the available tasks and configs. I almost didn't use it because it seemed to be missing some key features (mainly around mapping routes), but fortunately I discovered the additional tasks after adding the plugin to my build.gradle.   Some of the missing tasks includes:

```
- cfMap
- cfUnMap
- cfSwapDeployed
- cfDeleteOrphanedRoutes
- cfLogs
```

Also, for the `cloudfoundry { }`config block, you need to include the `application` field, which allows for setting the application name. 

I suppose the same goes for the Maven plugin since they're from the same code, but I haven't confirmed they're available.

**Comment by mamorrison** [comment]
Hi Tony-- many thanks for the head-up on Gradle CF plugin docs. Feel free to do a pull request to fix this yourself.  Otherwise, we on the CF docs team have some questions we'd like to ask you about this issue to point us toward the fixes it needs. What would be the best way to get in touch?  Thanks again!

**Comment by tonycapone** [comment]
Sorry I was busy this month with a wedding and didn't see this. I can put together a pull request in the next few days.

**Comment by bentarnoff** [comment]
Hey @tonycapone, we wanted to check in on this. We'd be grateful for that pull request! Thanks.

**Comment by bentarnoff** [comment]
Hi @tonycapone, I'm closing this issue because it's been awhile since we've heard from you. When you get a chance, please submit a PR to improve the documentation. Thanks.
