### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-buildpacks#47]
`docs-dev-guide/deploy-apps/environment-variable.html.md.erb` doesn't have an anchor called `#dea-set`. That's why Bookinder reports a broken link for `docs-buildpacks/node/node-tips.html.md.erb`.

**Comment by abbyachau** [comment]
Thanks @mastertinner. We've edited the docs-buildpacks/node/node-tips.html.md.erb page so that it includes a new anchor reference.

**Comment by mastertinner** [comment]
Thanks for the quick fix, @abbyachau!
