### ISSUE TITLE
Create a Rake Task should be more descriptive

### ISSUE THREAD

**Issue by lyanco** [cloudfoundry/docs-buildpacks#48]
https://github.com/cloudfoundry/docs-buildpacks/blob/615f5b4a68ca5071330e91608f29cba3a05e049e/ruby/ruby-tips.html.md.erb#L89

"Create a rake task" should link to external documentation for how to do this. Not obvious that cf:on_first_instance is not just boilerplate.

**Comment by jvshahid** [comment]
> "Create a rake task" should link to external documentation for how to do this.

The following steps explains how to create the rake task and how to use it in the app manifest. What am I missing ?

**Comment by flavorjones** [comment]
I'm also confused. @lyanco can you help us understand what you think needs to be changed?

**Comment by lyanco** [comment]
From a newb's perspective, it would be nice to have the file/folder structure that the rake task belongs in. Where do you create it? What should the file be called?

As a general note, might be nice to include file/folder structure for every code snippet, like the Michael Hartl Rails tutorial does (see the box title at https://www.railstutorial.org/book/rails_flavored_ruby#code-application_layout_redux).

**Comment by bentarnoff** [comment]
Thanks, @lyanco. We've added an extra step to clarify that developers must create a Rakefile if they do not already have one in order to add Rake tasks. We're closing this issue but please let us know if you have any additional feedback.
