### ISSUE TITLE
Insufficient details about play service bindings

### ISSUE THREAD

**Issue by dkowis** [cloudfoundry/docs-buildpacks#76]
https://github.com/cloudfoundry/docs-buildpacks/blob/master/java/play-service-bindings.html.md.erb

Does this work with play 2.x ? 

Is this documentation correct:
https://www.playframework.com/documentation/2.5.x/Deploying-CloudFoundry#Connecting-to-Cloud-Foundry-Services

I'm finding that it doesn't seem to be correct with a play 2.5.x application. I don't have the `cloud.services` properties available, and it's making it pretty much impossible to run a play application using any services on play. :(

**Comment by ishwar1987** [comment]
Hi Dkowis.
what is an updated . I also need to use cloud.service in application.conf. Did you get any solution?
Thanks in advance

**Comment by dkowis** [comment]
https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/pull/58

Only if you use play 2.3 it seems. 2.4 and beyond have made substantial changes to the way play is started up and things don't work any more.

**Comment by jncd** [comment]
@dkowis and @ishwar1987 Thanks for your comments. Yes, we support running Play Framework applications up to and including 2.4.x. The Play JPA plugin auto-reconfiguration works over that range as well. There were big changes to 2.5 and we haven’t started testing against it. At the very least we know that the auto-reconfiguration does not work, but most likely applications will at least start. 
I'll update the topic "Configuring Service Connections for Play Framework" to say that currently our Play support is for 2.4.x and earlier.

**Comment by dkowis** [comment]
From my personal experience, they do start, but you don't get the service variables for configuration. Makes it hard to configure things for the database. :( maybe the pull request I put in will make sure the service var works. 

We will have to do something completely different for 2.5 onward because slick doesn't use jpa at all. 

On August 24, 2016 7:33:30 PM CDT, Jane Day <notifications@github.com> wrote:
>@dkowis and @ishwar1987 Thanks for your comments. Yes, we support
>running Play Framework applications up to and including 2.4.x. The Play
>JPA plugin auto-reconfiguration works over that range as well. There
>were big changes to 2.5 and we haven’t started testing against it. At
>the very least we know that the auto-reconfiguration does not work, but
>most likely applications will at least start. 
>I'll update the topic "Configuring Service Connections for Play
>Framework" to say that currently our Play support is for 2.4.x and
>earlier.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cloudfoundry/docs-buildpacks/issues/76#issuecomment-242249521

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jncd** [comment]
@dkowis We'll clarify the 2.4.x support only for now in the doc, but going forward, @nebhale is a good person to follow up with about functionality.

**Comment by dkowis** [comment]
Yep I've been talking to him. :) I had a pull request that I referenced, but it broke too many things. Need to spend some more time on it. 

On August 25, 2016 11:58:47 AM CDT, Jane Day <notifications@github.com> wrote:
>@dkowis We'll clarify the 2.4.x support only for now in the doc, but
>going forward, @nebhale is a good person to follow up with about
>functionality. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cloudfoundry/docs-buildpacks/issues/76#issuecomment-242463335

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
