### ISSUE TITLE
Additional configuration section in cloudFoundry does not work.

### ISSUE THREAD

**Issue by ljubisap** [cloudfoundry/docs-buildpacks#79]
Hi,

In this page https://docs.run.pivotal.io/buildpacks/java/build-tool-int.html in "Additional Configuration" section is explained how to add additional configuration to cloudFoundry section. However when executed cfBind command following exception occurred:

`MUCM31654558A:edge ljubisap$ ./gradlew cfBind edge-v1-green rsyslog
FAILURE: Build failed with an exception.
Where:
Script '/Users/d061177/work/argonauts/edge/deploy.gradle' line: 73
What went wrong:
A problem occurred evaluating script.
Could not find method serviceInfos() for arguments [deploy_6x6bd8kd2vnh2x19p5s2uo8h7$_run_closure3_closure5@78065fcd] on root project 'edge'.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED`

Correct version of Gradle is set and cloudFoundry section looks like this:

`cloudfoundry {
        application = "$appName-$apiVersion"
        username = 'team-acid@me.com'
        space = 'acid'
        hosts = [application]
        buildpack = "java_buildpack"
        instances = 1
        memory = 1024
        healthCheckTimeout = 180
        command = ''
        file = getWarFile()
        trustSelfSignedCerts = true
        variants = ['-blue', '-green']
        env << [
                        APP_NAME               : application, // it's required for logging
                        APP_VERSION            : buildVersion, // it's required for logging
                        TEAM_NAME              : space, // folder  under which riemann statistics will be available
                        ENV_NAME               : organization,  // folder  under which riemann statistics will be available
                        DYNATRACE_AGENT_NAME   : "yaas_" + organization + "_" + application,
                        JBP_CONFIG_OPEN_JDK_JRE: "[memory_heuristics: {heap: 20, metaspace: 4}]",
                        MONITORING_POLLING_TIME: "120",
                        MONITORING_ENABLED     : true
                        // for details how to tune memory see https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml
                        // still you can use JAVA_OPTS : "-XX:MaxHeapFreeRatio=85" directly
        ]
        serviceInfos {
                "syslog" {
                        label = "syslog"
                        plan = "small_plan"
                        bind = true
                }
        }
}`

I tried with Gradle version 1.1.3, but got the same exception.

Any hints?

Ljubisa.

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @ljubisap. @Dannyzen and @RochesterinNYC, any thoughts on this?

**Comment by RochesterinNYC** [comment]
This seems like the domain of the java buildpack. @nebhale

**Comment by ljubisap** [comment]
Thank you for quick response.
I understand the exception, it happens in Java as well, but I do not know where serviceInfos() method suppose to come from. I tried few versions of gradle but that did not change anything. Method is still missing.

**Comment by bentarnoff** [comment]
@nebhale Do you have any thoughts on the problems experienced by @ljubisap above? Please let us know if there's something you think should be reflected in the documentation for the Java buildpack. Thanks.

**Comment by ljubisap** [comment]
@Dannyzen  @RochesterinNYC @nebhale @bentarnoff any thoughts so far?

**Comment by nebhale** [comment]
The issue isn't related to the Java Buildpack, as it is part of the build on the client.  There might be an issue with the use of the Gradle plugin, which is documented [here](https://github.com/cloudfoundry/cf-java-client/tree/1.x/cloudfoundry-gradle-plugin).
