### ISSUE TITLE
Disconnected Environments references are confusing

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/docs-buildpacks#83]
I've noticed a reference to the [Disconnected Environments](https://github.com/cloudfoundry/buildpack-packager/blob/master/doc/disconnected_environments.md) documentation from a few of the buildpack pages, saying that "your application must ‘vendor’ its dependencies". I know that the Python, Ruby, and Node buildpacks (did?) install the respective application dependencies as part of the build step, so was wondering:

* Is this sentence a recommendation, or a requirement?
* Is this relevant for _all_ Cloud Foundry deployments, or just ones in "disconnected environments"?

Thanks!

**Comment by Dannyzen** [comment]
Hey @afeld Thanks for reaching out.  Disconnected environments are environments which do not have access to the internet.  If dependencies were not vendored in an application then package managers that are configured to use the internet to download packages would not be able to. Thus, it is recommended that applications in disconnected environments vendor their dependencies.

With regards to environments with internet access, vendoring dependencies is optional and is not required as the appropriate package manager will take responsibility for obtaining an application's dependencies.
