### ISSUE TITLE
ruby-environment.html.md.erb links to 404ing blog post

### ISSUE THREAD

**Issue by davidillsley** [cloudfoundry/docs-buildpacks#87]
ruby-environment.html.md.erb includes a link to http://blog.cloudfoundry.com/2012/10/02/polishing-cloud-foundrys-ruby-gem-support which is currently 404ing.

The content does appear to have been captured by archive.org at https://web.archive.org/web/20130829153815/http://blog.cloudfoundry.com/2012/10/02/polishing-cloud-foundrys-ruby-gem-support/ but I'm not enough of an expert to know if it's still accurate and worth linking to directly.

**Comment by bentarnoff** [comment]
Thanks, @davidillsley! @Dannyzen @RochesterinNYC any sense of what the correct link should be?

**Comment by RochesterinNYC** [comment]
@bentarnoff I think this might be it? https://blog.pivotal.io/pivotal-cloud-foundry/products/polishing-cloud-foundrys-ruby-gem-support

**Comment by bentarnoff** [comment]
Great, thanks @RochesterinNYC !

**Comment by bentarnoff** [comment]
@davidillsley We've fixed the link, and you can view the change on our staging site here: http://docs-cloudfoundry-staging.cfapps.io/buildpacks/ruby/ruby-environment.html. The change should be live on our production site soon. Thanks!
