### ISSUE TITLE
Can you elaborate more regarding auto configuration

### ISSUE THREAD

**Issue by ishwar1987** [cloudfoundry/docs-buildpacks#92]
Hi,
I need to use the auto configuration features in my play application . So can you help me how i can do it.
If you can provide detailed documentation regarding this .

Thanks in advanced.

**Comment by jncd** [comment]
hi @ishwar1987

**Comment by ishwar1987** [comment]
Hi ,
I have posted auto configuration error in play 2.3 here. https://github.com/cloudfoundry/java-buildpack/issues/322.  Do i miss anything?

Thanks in advanced.

**Comment by jncd** [comment]
Hi @ishwar1987 Good that you've asked your questions in the java buildpack repo. I'll go ahead and close this docs issue for now. And, of course, you can later make a pull request against the docs if you want to contribute what you learn.
