### ISSUE TITLE
how do you skip-ssl-validation using cloudfoundry gradle plugin?

### ISSUE THREAD

**Issue by marsinvasion** [cloudfoundry/docs-buildpacks#93]
Is there an option to skip ssl validation using cloudfoundry gradle plugin?

Using the command line client, we can use the --skip-ssl-validation option

`> I/O error on GET request for :sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by bentarnoff** [comment]
Hey @marsinvasion thanks for this. @sclevine @RochesterinNYC do you have any thoughts on this?

**Comment by jchesterpivotal** [comment]
This looks like a Java buildpack question to us. @nebhale, what say you?

**Comment by nebhale** [comment]
According to [the documentation](https://github.com/cloudfoundry/cf-java-client/tree/1.x/cloudfoundry-gradle-plugin#self-signed-ssl-certificates) `trustSelfSignedCerts=true`.

**Comment by bentarnoff** [comment]
Thanks, @nebhale! Hey @marsinvasion I'm closing this issue for now but please feel free to get in touch if you have any further questions.

**Comment by marsinvasion** [comment]
Thanks guys
