### ISSUE TITLE
"Enable or Disable Basic Authentication" doesn't explain environment variable settings

### ISSUE THREAD

**Issue by jeffsouthard** [cloudfoundry/docs-buildpacks#94]
re: docs-buildpacks/staticfile/index.html.md.erb

The first line of the "Enable or Disable Basic Authentication" section says:

"Protect your website with a user/password configured via environment variables." but does NOT mention any need to set environment variables in the rest of the section.

That should be rephrased. OR, if environment variables must be set, then explain it.

I followed the instructions carefully and could not get basic authentication working. Now I'm wondering if I need to set environment variables.

**Comment by pspinrad** [comment]
@jeffsouthard Hey yeah, that isn't explained-- sorry and thanks for spotting.  Finding out...

**Comment by pspinrad** [comment]
Turns out there isn't an env var that controls basic auth-- it all depends on the presence / absence of the `Staticfile.auth` file. Correcting in docs now...
